def get_full_replacements():
    r = {
        "A1. Tên đơn vị chủ quản hệ thống thông tin (*)  Xã Nghi Kim, Tỉnh Nghệ An": "A1. Tên đơn vị chủ quản hệ thống thông tin (*)  {{ ten_don_vi }}",
        "A2. Tên hệ thống thông tin cần phân loại (*)  Hệ thống thông tin phục vụ hoạt động của UBND xã Nghi Kim": "A2. Tên hệ thống thông tin cần phân loại (*)  {{ he_thong_thong_tin }}",
        "A3. Địa chỉ trụ sở chính (*)  Xóm 13B, Xã Nghi Kim. Nghệ An": "A3. Địa chỉ trụ sở chính (*)  {{ dia_chi }}",
        "A4. Số điện thoại cơ quan: 0123 456 789": "A4. Số điện thoại cơ quan: {{ so_dien_thoai_co_quan }}",
        "A5. Email cơ quan: vanthu.lynhan.gov.nghean.vn": "A5. Email cơ quan: {{ email_co_quan }}",
        "Ông Ngọc Nguyễn – Chủ tịch Ủy Ban Nhân dân xã Nghi Kim": "{{ A6_ho_ten_thu_truong }} – {{ A6_chuc_vu_thu_truong }}",
        "QĐ số 45/QĐ-UBND ngày 10/3/2024 của UBND xã Nghi Kim": "{{ A7_so_qd_nhiem_vu }}",
        "Trung tâm CNTT & TT tỉnh Nghệ An": "{{ B2_don_vi_ho_tro }}",
        "Hệ thống phục vụ hoạt động hành chính của UBND xã: xử lý hồ sơ một cửa (DVCTT), quản lý văn bản điều hành, lưu trữ dữ liệu dân cư, trao đổi email nội bộ": "{{ C1_mo_ta_chuc_nang }}",
        "Cán bộ công chức xã (33 người), người dân đến giao dịch một cửa, UBND xã.": "{{ C2_doi_tuong_nguoi_dung }}",
        "Dữ liệu cá nhân (CMND, địa chỉ, số điện thoại); hồ sơ hộ tịch; hồ sơ đất đai; văn bản hành chính (không mật).": "{{ C3_loai_du_lieu }}",
        "Nội bộ: 33 cán bộ; Bên ngoài: ~200 lượt/tháng (người dân qua cổng DVCTT)": "Nội bộ: {{ C5_noi_bo }} cán bộ; Bên ngoài: {{ C5_ben_ngoai }}",
        "Năm 2025": "năm {{ C6_nam_hoat_dong }}",
        "iGate 10.66.138.209": "{{ D2_router_modem }}",
        "10.66.138.210": "{{ D3_ip_lan_gateway }}",
        "Có (đã liệt kê ở bảng trên)": "{{ E2_firewall_cung_co }} Có (đã liệt kê ở bảng trên)",
        "NVR Dahua Model NVR2108HS-8P-I2, S/N: 9Cxxxxxxxx, đặt tại Tầng 1 – Phòng CNTT (P.102)": "{{ G2_dau_ghi_camera }}",
        "30 ngày (ổ cứng 4TB)": "{{ G3_luu_tru_camera }}",
        "192.168.1.0/24 (máy tính nhận IP từ DHCP: 192.168.1.100 – 192.168.1.200)": "{{ H1_dai_ip_lan }}",
        "192.168.1.1": "{{ H2_gateway_ip }}",
        "8.8.8.8 (Google) hoặc DNS của Viettel: 203.113.131.1": "{{ H3_dns_server }}",
        "Không có VLAN (toàn bộ thiết bị cùng một mạng phẳng)": "{{ H4_vlan_khong }} Không có VLAN (toàn bộ thiết bị cùng một mạng phẳng)",
        "Có khóa cửa (chìa khóa thường)": "{{ L1_khoa_cua_thuong }} Có khóa cửa (chìa khóa thường)",
        "Không (ký tên)": "{{ L1_ky_ten_khong }} Không",
        "Ổ cứng ngoài WD 2TB – cắm tại máy chủ, sao lưu mỗi thứ Sáu hàng tuần": "{{ L4_2_vi_tri_luu_tru }}",
        "Gọi đơn vị ngoài": "{{ L6_2_phuong_thuc_xu_ly }}",
        "Cổng 443 mở để truy cập ứng dụng DVCTT; Cổng 37777 mở để xem camera từ xa (NVR Dahua)": "{{ L7_4_cong_mo }}",
        "Phòng CNTT khoảng 15m², có khóa cửa, 2 người có chìa: cán bộ CNTT và Chủ tịch UBND": "{{ L8_4_mo_ta_phong }}",
        "Kết nối đến Cổng DVCTT tỉnh Bình Thuận qua HTTPS; Kết nối VPN đến Hệ thống quản lý văn bản eCabinet (SSL VPN do Sở TTTT cấp)": "{{ P3_1_phuong_thuc_ket_noi }}",
        "Cán bộ CNTT xã tự cập nhật; đối với thiết bị mạng do Trung tâm CNTT&TT tỉnh hỗ trợ": "{{ Q3_ai_cap_nhat }}",
        "Router Viettel: do Viettel bảo trì định kỳ 6 tháng/lần; Switch: chưa cập nhật firmware": "{{ Q4_firmware_update }}",
        "Quý IV/2025 – do Sở TTTT Bình Thuận thực hiện theo kế hoạch năm": "{{ S2_ke_hoach_tiep_theo }}",
        "SSID: 'UBND-SongLuy' / Bảo mật: WPA2-PSK / Không có mạng khách riêng": "{{ T1_3_thong_tin_wifi }}",
        "Từ trên xuống: (1) Patch panel 24 cổng; (2) Switch Dahua 16P; (3) Router Viettel; (4) NVR Camera; (5) UPS APC 1500VA": "{{ T3_2_thiet_bi_trong_tu }}",
        "Cáp quang GPON từ cột điện vào ONU/Modem Viettel GW240H-V2 đặt tại Phòng CNTT tầng 1": "{{ T4_2_cap_tu_isp }}",
        "Trương Tuấn Lực": "{{ A6_ho_ten_thu_truong }}",
        "Đỗ Văn Hân": "{{ nguoi_khao_sat }}",
    }
    
    # Checkbox labels mapping
    glyph_map = {
        "Cá nhân thông thường": "C4_du_lieu_ca_nhan_thuong",
        "Dữ liệu cá nhân thông thường": "C4_du_lieu_ca_nhan_thuong",
        "Dữ liệu cá nhân nhạy cảm": "C4_du_lieu_ca_nhan_nhay_cam",
        "Dữ liệu công (không bao gồm cá nhân)": "C4_du_lieu_cong",
        "Không xác định / Cần tư vấn": "C4_khong_xac_dinh",
        "Có – Tên hệ thống: ___________________________": "C7_co",
        "Không (C7)": "C7_khong",
        "Không (C8)": "C8_khong",
        "Có – Độ mật: ___________": "C8_co",
        "Không – Sử dụng tính năng firewall tích hợp trên Router/Switch": "E2_firewall_router",
        "Không – Sử dụng phần mềm firewall trên máy chủ": "E2_firewall_phan_mem",
        "Không (F3)": "F3_khong",
        "Có – Tên dịch vụ / nhà cung cấp: _________________________": "F3_co",
        "Có VLAN – Số lượng VLAN: ___   Mô tả: ___________________________": "H4_vlan_co",
        "Có khóa cửa + camera giám sát": "L1_khoa_camera",
        "Có thẻ từ / kiểm soát điện tử": "L1_the_tu",
        "Không có kiểm soát riêng": "L1_khong_kiem_soat",
        "Có (L1_ky)": "L1_ky_ten_co",
        "Có – Yêu cầu: độ dài tối thiểu _____ ký tự, đổi định kỳ _____ tháng": "L2_pass_policy_co",
        "Không có chính sách thống nhất (mỗi người tự đặt)": "L2_pass_policy_khong",
        "Mỗi cán bộ có tài khoản riêng": "L2_account_rieng",
        "Dùng chung một tài khoản admin": "L2_account_chung",
        "Cả hai hình thức": "L2_account_both",
        "Có – Áp dụng cho: ___________________________": "L2_2fa_co",
        "Không (L2_2fa)": "L2_2fa_khong",
        "Có – Tên phần mềm: _______________  Bản quyền: Có / Không / Miễn phí": "L3_antivirus_co",
        "Không (L3)": "L3_antivirus_khong",
        "Có – Tần suất: Hàng ngày / Hàng tuần / Hàng tháng": "L4_1_tan_suat_co",
        "Thực hiện thủ công khi nhớ": "L4_1_tan_suat_thu_cong",
        "Không sao lưu": "L4_1_tan_suat_khong",
        "Có – Địa điểm: ___________________________": "L4_3_khac_vi_tri",
        "Không – Cùng vị trí với máy chủ": "L4_3_khong_khac_vi_tri",
        "Có (L5_1)": "L5_1_log_router_co",
        "Không biết / Chưa kiểm tra": "L5_1_log_router_khong_biet",
        "Không (L5_1)": "L5_1_log_router_khong",
        "< 3 tháng": "L5_2_thoi_gian_duoi_3",
        "3 – 6 tháng": "L5_2_thoi_gian_3_6",
        "> 6 tháng": "L5_2_thoi_gian_tren_6",
        "Không lưu": "L5_2_thoi_gian_khong",
        "Có – Tên/loại: ___________________________": "L5_3_siem_co",
        "Không (L5_3)": "L5_3_siem_khong",
        "Không có sự cố nào": "L6_1_su_co_khong",
        "Có – Mô tả ngắn: ___________________________": "L6_1_su_co_co",
        "Không biết / Không ghi nhận": "L6_1_su_co_khong_biet",
        "Tường lửa tích hợp trên Router (SPI – Stateful Packet Inspection)": "L7_1_firewall_router",
        "Tường lửa phần cứng chuyên dụng (Firewall appliance)": "L7_1_firewall_phanh_cung",
        "Tường lửa phần mềm trên máy chủ (iptables, Windows Firewall…)": "L7_1_firewall_phan_mem",
        "Chặn tất cả, chỉ cho phép những gì được khai báo (Default Deny – Khuyến nghị)": "L7_2_policy_deny",
        "Cho phép tất cả, chỉ chặn những gì bị cấm (Default Allow)": "L7_2_policy_allow",
        "Không biết / Chưa cấu hình": "L7_2_policy_khong_biet",
        "Có – qua VPN (SSL VPN / IPSec)": "L7_3_remote_vpn",
        "Có – qua Remote Desktop / TeamViewer / AnyDesk": "L7_3_remote_desktop",
        "Không (L7_3)": "L7_3_remote_khong",
        "Có – Hãng/Model: _______________  Công suất: _______VA  Thời gian dự phòng: ~_____phút": "L8_1_ups_co",
        "Không có UPS": "L8_1_ups_khong",
        "Có – Điều hòa hoạt động 24/7": "L8_2_air_24_7",
        "Có – Chỉ bật giờ hành chính": "L8_2_air_hanh_chinh",
        "Không (L8_2)": "L8_2_air_khong",
        "Có – Loại: (L8_3)": "L8_3_chua_chay_co",
        "CO₂": "L8_3_co2",
        "Bột khô": "L8_3_bot_kho",
        "Khác: ___________": "L8_3_khac",
        "Không (L8_3)": "L8_3_chua_chay_khong",
        "HTTPS (có chứng chỉ SSL/TLS) – Khuyến nghị": "P1_https",
        "HTTP (không mã hóa)": "P1_http",
        "Cả hai (một số dùng HTTPS, một số dùng HTTP)": "P1_both",
        "SSL VPN": "P2_ssl_vpn",
        "IPSec": "P2_ipsec",
        "Khác: _____________": "P2_khac",
        "Không có VPN": "P2_khong",
        "VPN chuyên dụng (do Sở TTTT/tỉnh cấp)": "P3_vpn_chuyen_dung",
        "Internet thường (HTTPS)": "P3_internet_thuong",
        "Đường truyền số liệu chuyên dụng (MPLS/Leased Line)": "P3_duong_truyen_so_lieu",
        "Không kết nối trực tiếp": "P3_khong_ket_noi",
        "Có – Phần mềm/phương pháp: ___________________________": "P4_ma_hoa_co",
        "Không mã hóa dữ liệu lưu trữ": "P4_ma_hoa_khong",
        "Có – TLS/SMTPS (qua email.gov.vn hoặc tương đương)": "P5_email_sec_co",
        "Không biết (P5)": "P5_email_sec_khong_biet",
        "Không (P5)": "P5_email_sec_khong",
        "Hàng tháng": "Q1_thang",
        "Hàng quý": "Q1_quy",
        "Khi có cảnh báo": "Q1_canh_bao",
        "Khác (Q1)": "Q1_khac",
        "Không có quy trình – Cập nhật tùy lúc": "Q1_tuy_luc",
        "Không cập nhật (Q1)": "Q1_khong",
        "Có – Tự động": "Q2_tu_dong",
        "Có – Thủ công (khi nhớ)": "Q2_thu_cong",
        "Không cập nhật (Q2)": "Q2_khong",
        "Có – Nhận cảnh báo qua email/văn bản và xử lý": "Q5_canh_bao_co",
        "Không theo dõi thường xuyên": "Q5_canh_bao_khong",
        "Chưa biết kênh nhận cảnh báo": "Q5_canh_bao_chua_biet",
        "Có – Hình thức: ___________________________": "R2_dao_tao_co",
        "Không (R2)": "R2_dao_tao_khong",
        "Có – Máy chủ trong DMZ: ___________________________": "T1_1_dmz_co",
        "Không có DMZ – Tất cả thiết bị cùng 1 vùng LAN": "T1_1_dmz_khong",
        "Có – WiFi trên VLAN riêng / Subnet riêng (không truy cập được LAN máy chủ)": "T1_2_wifi_tach_rieng",
        "Không – WiFi cùng dải IP với máy tính văn phòng": "T1_2_wifi_chung",
        "Không có WiFi": "T1_2_wifi_khong",
        "Có – Camera trên VLAN/subnet tách biệt khỏi mạng máy tính": "T1_4_camera_tach_rieng",
        "Không – Camera cùng dải IP với máy tính văn phòng": "T4_camera_chung",
        "Không biết (T1_4)": "T1_4_camera_khong_biet",
        "Có – Kích thước rack: ___U  Vị trí: Tầng ___ – Phòng ___": "T3_1_rack_co",
        "Không – Thiết bị để trực tiếp trên bàn/giá đỡ": "T3_1_khong_rack",
        "Cáp đồng (UTP/STP Cat5e hoặc Cat6) – phổ biến nhất": "T4_1_cap_dong",
        "Cáp quang nội bộ (Fiber – nếu khoảng cách > 100m)": "T4_1_cap_quang",
        "Cả hai (cáp đồng trong phòng, cáp quang giữa tầng/tòa nhà)": "T4_1_both",
        "Đã có": "M_da_co",
        "Chưa có": "M_chua_co",
    }
    
    # Generate all variations for glyphs
    for glyph in ["☐", "☒", "☑", "x"]:
        for label, var in glyph_map.items():
            # Clean label context hints
            clean_label = label
            if '(' in label and ')' in label:
                # Basic context removal if needed, but here labels are mostly unique
                pass
            r[f"{glyph} {clean_label}"] = f"{{{{ {var} }}}} {glyph} {clean_label}"
            
    return r
