import os
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()

url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

if not url or not key:
    print("Missing Supabase credentials")
    exit(1)

supabase: Client = create_client(url, key)

def create_tables():
    # Table: staff
    try:
        supabase.table("staff").select("count", count="exact").limit(1).execute()
        print("Table 'staff' already exists.")
    except Exception:
        print("Creating table 'staff' (Note: This script can only check/insert, SQL creates tables).")
        # In Supabase, we usually use SQL Editor. I will provide the SQL to the user.
        # But I can try a dummy insert to see if it works.
        pass

    # Table: surveys
    try:
        supabase.table("surveys").select("count", count="exact").limit(1).execute()
        print("Table 'surveys' already exists.")
    except Exception:
        print("Table 'surveys' not found.")

if __name__ == "__main__":
    print(f"Checking Supabase at {url}...")
    # SQL to run in Supabase SQL Editor:
    sql = """
    -- Create staff table
    CREATE TABLE IF NOT EXISTS staff (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT UNIQUE NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- Create surveys table
    CREATE TABLE IF NOT EXISTS surveys (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ten_don_vi TEXT NOT NULL,
        doer TEXT NOT NULL,
        status TEXT DEFAULT 'Đang chờ',
        date TEXT,
        data JSONB DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- Insert default staff
    INSERT INTO staff (name) VALUES 
    ('Bảo Ngọc'), ('Anh Tuấn'), ('Minh Hùng'), ('Trung Kiên'), 
    ('Duy Khánh'), ('Văn Phương'), ('Đức Thắng')
    ON CONFLICT (name) DO NOTHING;
    """
    print("Please run the following SQL in your Supabase SQL Editor:")
    print(sql)
